### ISSUE TITLE
PersistenceContextInjectionTest needs update due to changes in JPA

### ISSUE THREAD

**Issue by manovotn** [jakartaee/cdi-tck#380]
Two methods in `PersistenceContextInjectionTest` are now incorrect:
* `testBeanTypesAndBindingTypesOfPersistenceContext`
* `testBeanTypesOfPersistenceUnit`

The reason being this commit from the JPA repo - https://github.com/eclipse-ee4j/jpa-api/commit/1ae01ae3793d129bf921e9b1fe893bed744065d8
Both, `EntityManager` and `EntityManagerFactory` now implement `AutoClosable` which will be included as a bean type in the test.

**Comment by manovotn** [comment]
FYI @Azquelt @arjantijms just to save you some headache - this is likely to be a problem in GF and Liberty as well.

**Comment by arjantijms** [comment]
Thanks for the heads-up @manovotn. We're tracking the remaining failures in https://github.com/eclipse-ee4j/glassfish/issues/23961
