### ISSUE TITLE
`InterceptorLifeCycleTest` should't require destory interceptors to be initialized at the instance creation

### ISSUE THREAD

**Issue by dstepanov** [jakartaee/cdi-tck#386]
`org.jboss.cdi.tck.interceptors.tests.contract.interceptorLifeCycle.InterceptorLifeCycleTest`

Cannot find any requirements for the interceptors (especially destroy once) to be initialized at the instance creation. It doesn't really make sense to require something like this.

**Comment by Ladicek** [comment]
I guess I probably agree it doesn't make much sense to require this (though there might be good reasons I'm not aware of), but the test itself is correct. The Interceptors specification https://jakarta.ee/specifications/interceptors/2.0/interceptors-spec-2.0.html#interceptor_life_cycle says:

> The lifecycle of an interceptor instance is the same as that of the target instance with which it is associated.
>
> Except as noted below, when the target instance is created, a corresponding instance is created for each associated interceptor class. These interceptor instances are destroyed if the target instance fails to be created or when the target instance is destroyed by the container.

I couldn't find any instance of "except as noted below" (happy to be proven wrong here), so it seems to me that the spec requires all interceptors to be instantiated when the target is instantiated.

**Comment by dstepanov** [comment]
I keep missing the interceptors spec. I guess we can close it, but it doesn't make sense to have such a requirement.

**Comment by manovotn** [comment]
> though there might be good reasons I'm not aware of

ATM, I can't think of any either, Might be a remnant of former implementations or former limitations. Interceptors are (or were?) also implemented by EJB so there might potentially be some reason there as well?

Either way, this is something that could be raised in the interceptors GH repo, so closing this issue.
