### ISSUE TITLE
TCK Challenge Tests with FailingHttpStatusCode exception

### ISSUE THREAD

**Issue by breakponchito** [jakartaee/cdi-tck#389]
**Specification:**
[cdi 4.0](https://jakarta.ee/specifications/cdi/4.0/)

**Challenged test(s):**
[org.jboss.cdi.tck.tests.context.application.async.ApplicationContextAsyncListenerTest#testApplicationContextActiveOnError](https://github.com/jakartaee/cdi-tck/blob/master/web/src/main/java/org/jboss/cdi/tck/tests/context/application/async/ApplicationContextAsyncListenerTest.java#L79)
[org.jboss.cdi.tck.tests.context.conversation.determination.ConversationDeterminationTest#testConversationDetermination](https://github.com/jakartaee/cdi-tck/blob/master/web/src/main/java/org/jboss/cdi/tck/tests/context/conversation/determination/ConversationDeterminationTest.java#L59)
[org.jboss.cdi.tck.tests.context.request.async.RequestContextAsyncListenerTest#testRequestContextActiveOnError](https://github.com/jakartaee/cdi-tck/blob/master/web/src/main/java/org/jboss/cdi/tck/tests/context/request/async/RequestContextAsyncListenerTest.java#L87)
[org.jboss.cdi.tck.tests.context.session.async.SessionContextAsyncListenerTest#testSessionContextActiveOnError](https://github.com/jakartaee/cdi-tck/blob/master/web/src/main/java/org/jboss/cdi/tck/tests/context/session/async/SessionContextAsyncListenerTest.java#L83)

**TCK version:**
4.0.5

**Tested implementation:**
[Payara 6 (branch)](https://github.com/breakponchito/Payara/tree/payara6-cdi-4.0-upgrade) with:

- WELD api: 5.0.Final
- WELD: 5.0.0.SP2
- CDI API: 4.0.1

**Description:**
The tests are failing because of the following exception thrown:  com.gargoylesoftware.htmlunit.FailingHttpStatusCodeException: 500 Internal Server Error

those tests are throwing ServletException as part of the flow to test and the Payara Server side is setting the 500 error, but on the TCK side with the htmlunit framework those errors are Wrapped by a new exception the FailingHttpStatusCodeException. This is the wrong behavior and we don't want to hack the server side to return different codes.

We saw a way to solve this but it is on the TCK side by setting the following property to false:  webClient.getOptions().setThrowExceptionOnFailingStatusCode(false)

With this value set to false all the failing tests will pass without hack the server side

**Error Logs:**
[error-logs.txt](https://github.com/jakartaee/cdi-tck/files/8972240/error-logs.txt)

**Comment by manovotn** [comment]
This challenge is linked to a discussion on mailing list which started with this post - https://www.eclipse.org/lists/cdi-dev/msg00618.html

IIRC, for the sake of TCK test it doesn't even matter if the returned code of 200 or 500 (the code isn't checked at all).
Therefore, we could change it by adding the suggested option to web client and ignore the failure.

Whether this is right or wrong is a good question for someone from servlet spec I guess (does anyone know who to `@mention` here?). It is about an HTTP servlet supporting async and [turning a request async with attached listener](https://github.com/jakartaee/cdi-tck/blob/master/web/src/main/java/org/jboss/cdi/tck/tests/context/request/async/AsyncServlet.java#L71-L72). The request, for some tests, [results in an error](https://github.com/jakartaee/cdi-tck/blob/master/web/src/main/java/org/jboss/cdi/tck/tests/context/request/async/AsyncServlet.java#L79-L80) that is going through yet another servlet.

Note that in the mailing thread, most participating people opted towards current TCK setup being correct from Servlet specification PoV. But also noted that the spec might need clarifications in this regard.

**Comment by arjantijms** [comment]
@markt-asf is the one to mention here, but he already answered the question in the email thread.

When a Servlet throws an exception  during an async process, should the response be automatically set to 500, or is it the responsibility of the error handler to set the 500 (or other code). That's the main question.

Might also be good to compare what plain Tomcat is doing here, even though it doesn't run the CDI TCK; just create a similar situation with an async request and exception and check what gets send to the client.

**Comment by breakponchito** [comment]
@manovotn  @arjantijms Hi guys, Do you have any update on this?. On our side we exclude the test from our arquillian tck configuration

**Comment by breakponchito** [comment]
@arjantijms I'm going to review today, thanks. I'll let you know my findings

**Comment by breakponchito** [comment]
I already tested the servlet async call on tomcat throwing ServletException and it is showing 500 error

![image](https://user-images.githubusercontent.com/279375/179292772-7375d184-2c71-443e-8068-5061efe54f52.png)
this means that the correct way to deal with async errors is to propagate to the client, is that ok? I think this challenge is valid. Who can help with this?

**Comment by breakponchito** [comment]
Do you mean to add the change to the following TCK tests?  
[org.jboss.cdi.tck.tests.context.application.async.ApplicationContextAsyncListenerTest#testApplicationContextActiveOnError](https://github.com/jakartaee/cdi-tck/blob/master/web/src/main/java/org/jboss/cdi/tck/tests/context/application/async/ApplicationContextAsyncListenerTest.java#L79)
[org.jboss.cdi.tck.tests.context.conversation.determination.ConversationDeterminationTest#testConversationDetermination](https://github.com/jakartaee/cdi-tck/blob/master/web/src/main/java/org/jboss/cdi/tck/tests/context/conversation/determination/ConversationDeterminationTest.java#L59)
[org.jboss.cdi.tck.tests.context.request.async.RequestContextAsyncListenerTest#testRequestContextActiveOnError](https://github.com/jakartaee/cdi-tck/blob/master/web/src/main/java/org/jboss/cdi/tck/tests/context/request/async/RequestContextAsyncListenerTest.java#L87)
[org.jboss.cdi.tck.tests.context.session.async.SessionContextAsyncListenerTest#testSessionContextActiveOnError](https://github.com/jakartaee/cdi-tck/blob/master/web/src/main/java/org/jboss/cdi/tck/tests/context/session/async/SessionContextAsyncListenerTest.java#L83)

**Comment by manovotn** [comment]
> for all of them we just need to set the following property as false:
webClient.getOptions().setThrowExceptionOnFailingStatusCode(false)

Yes, that's exactly what I meant.

> Claims that a test asserts requirements over and above that of the specification

The test doesn't assert on return value of `webClient.getPage(getPath(AsyncServlet.TEST_ERROR));` in any way.
The exception is a byproduct of this call, instead, CDI TCK tests that on error listeners are invoked which is defined and works.
Hence why I said I think it is invalid.

**Comment by Pandrex247** [comment]
I'm still unclear on how this is an invalid challenge.
It's not directly asserting on it, but the test **requires** that the server not return a failing status code (on a request that _failed_), and no specification defines that it must behave this way. 

Since you're rejecting the challenge, and given that we can't pass the TCK unless we modify Payara specifically for this test, we would need a service release of the TCK ASAP please.

**Comment by manovotn** [comment]
> It's not directly asserting on it, but the test requires that the server not return a failing status code

The test doesn't care what it returns, it makes no assertions on status code and has been like this for a long time.
The only reason why this now fails for some implementations is probably https://github.com/jakartaee/cdi-tck/commit/0f9f0a484f10903e484b676e6bcea62ec97e91e3 which updated htmlunit version and they seem to have changed their default behavior. Hence we are now seeing this bug.

> Since you're rejecting the challenge, and given that we can't pass the TCK unless we modify Payara specifically to satisfy this test, we would need a service release of the TCK ASAP please.

I am not sure why does it matter so much whether it is or isn't challenge but we can sure cut a release.
In fact any CDI committer (which @breakponchito seems to be?) can do that via Eclipse CI - https://ci.eclipse.org/cdi/
If you want me to do that, then I'll get to it tomorrow morning :)

**Comment by Pandrex247** [comment]
I think we're talking around each other now :P
The test cares what the server returns by nature of the update to htmlunit, which now throws an exception on a non-200 return code and thus fails the test (since the exception is not caught) - as you say it's essentially a bug in the test that only affects specific implementations 👍

It matters if the challenge is rejected because it means we can't exclude the test from runs of the TCK and still attempt to certify - we'd be stuck until a new version of the 4.0.x TCK was released with the merged fix.
If we're looking at doing a release of the TCK that quickly though then yes the problem goes away 😊
