### ISSUE TITLE
Fix the LangModelTckTest test

### ISSUE THREAD

**Issue by OndroMih** [jakartaee/cdi-tck#392]
GlassFish is failing the LangModelTckTest added in CDI TCK 4.0.5 with the https://github.com/jakartaee/cdi-tck/pull/382 PR. It seems to me that the test is wrong and doesn't include the `org.jboss.weld.lang.model.tck.LangModelExtension` class in the deployment.

GlassFish fails the deployment with the following message:

```
org.glassfish.deployment.common.DeploymentException: CDI deployment failure:jakarta.enterprise.inject.build.compatible.spi.BuildCompatibleExtension: Provider org.jboss.weld.lang.model.tck.LangModelExtension not found
	at org.glassfish.weld.WeldDeployer.event(WeldDeployer.java:442)
	at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:107)
	at org.glassfish.internal.data.ApplicationInfo.load(ApplicationInfo.java:332)
```

More info about the failure in [this Jenkins job run](https://ci.eclipse.org/jakartaee-tck/job/guru/job/jakarta-cdi-model-tck-glassfish-run-guru/org.jboss.weld$lang-model-tck-runner/lastCompletedBuild/testReport/org.jboss.weld.lang.model.tck/LangModelTckTest/testLangModel/).

The test adds `LangModelExtension` into a service file with ([on line 53](https://github.com/jakartaee/cdi-tck/blob/4.0.5/dist-build/lang-model-tck-runner/src/test/java/org/jboss/weld/lang/model/tck/LangModelTckTest.java#L53)) but doesn't add the class into the deployment. This isn't done automatically. GlassFish then finds the service file and attempts to load the `LangModelExtension` class but it's not on the classpath.

**Comment by OndroMih** [comment]
I believe that no new tests should be added in a patch release. Some implementations are already certified with an older 4.0 CDI TCK and might fail this new test. 

I suggest that the `LangModelTckTest` is removed in a new 4.0.6 release and added back to be released in the next minor or major CDI release (after Jakarta EE 10).

Alternatively, all certified implementations should be certified again against 4.0.5 CDI TCK or newer to ensure that they pass the TCK even with this new test. Then I believe we can safely leave the new test in a patch release. But I still think it needs to be fixed, otherwise no implementation will pass it.

**Comment by manovotn** [comment]
To be fair, I had no idea @starksm64 added copy of Weld's lang model execution setup directly into TCK repo.
We shouldn't use `weld` package there either.

And you are correct that the class should be part of the deployment.

> I believe that no new tests should be added in a patch release. Some implementations are already certified with an older 4.0 CDI TCK and might fail this new test.

It was always intended that implementations need to pass lang model TCKs as they are literally required for build compatible extensions to work.
That being said, I am not sure test such as this is worth much as all impl can do the setup as they need, the TCK test should only have a general guideline on how to execute it. Which is already captured in [README](https://github.com/jakartaee/cdi-tck/blob/4.0.5/lang-model/README.adoc) at least.

Am I right @Ladicek?

**Comment by manovotn** [comment]
@OndroMih since you mentioned (via mail) that this i blocking you, can you confirm that adding the `LangModelExtension` into the deployment fixes the problem for you?

We could do a TCK release with that (all commiters in this repo can do that via Jenkins job) as a fix for now and then discuss if we want to address this in some other way.

**Comment by starksm64** [comment]
The documentation around the lang model tck has been there from the 4.0.0 release, with the section that recommends running the tck using a build model extension, so I would not say there has been any addition in a minor release. What has happened was clarifying the requirement to run, including the lang model tck artifact and an example runner in the dist. I'm fine with accepting a challenge as the current description being unusable, but not to the point that it prevents inclusion of the lang model tck in the 4.0.x release series. The lang model tck is handled similar to how the dependency injection tck is handled. There is a test artifact that needs to be run, and there is a recommendation on how to do this, but it is not as simple as setting up a surefire configuration to run.

**Comment by OndroMih** [comment]
> The documentation around the lang model tck has been there from the 4.0.0 release, with the section that recommends running the tck using a build model extension, so I would not say there has been any addition in a minor release. What has happened was clarifying the requirement to run, including the lang model tck artifact and an example runner in the dist.

I'm not very familiar with the CDI TCK, at least not with the changes in 4.0. I thought that `LangModelTckTest` was a test in the TCK but now I undeerstand that it's just an example of how the CDI Language Model TCK should be set up. I assume that for GlassFish, we can just modify the `LangModelTckTest` class in the example runner and it's not a violation of the TCK requirements, am I right, @starksm64 ?

**Comment by starksm64** [comment]
Yes, that is correct.

**Comment by OndroMih** [comment]
Then I'll close this issue, thanks.

I think the confusion happened due to everybody in a hurry to pass the TCK with GlassFish and start a ballot for Jakarta EE 10 ASAP. I read the CDI TCK guide and it clearly states that the Weld Test Runner is just an example project, so the instructions are fine for me. The test class in the runner could be improved but let's wait until GlassFish passes the TCK and then we'll know moe what needs to be improved.

**Comment by arjantijms** [comment]
For anyone following this, GF now passes the CDI Lang Model TCK: https://github.com/eclipse-ee4j/glassfish/pull/24040
