### ISSUE TITLE
org.jboss.cdi.tck.interceptors.tests.bindings.aroundConstruct.ConstructorInterceptionTest

### ISSUE THREAD

**Issue by jeanouii** [jakartaee/cdi-tck#418]
Per the current [TCK Process documentation](https://jakarta.ee/committees/specification/tckprocess/), please find bellow a challenge related to CDI TCK. Can someone please add the `challenge` label which is required by the TCK Process but not available to everyone to add.

### The relevant specification version and section number(s)

https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html
Section 1.2.5. Relationship to Jakarta Interceptors

https://jakarta.ee/specifications/interceptors/2.1/jakarta-interceptors-spec-2.1.html
Section 5.2.1. Use of the Priority Annotation in Ordering Interceptors

### The coordinates of the challenged test(s)

Only following tests in the class are related to the challenge 

* testMultipleConstructorLevelBinding
* testTypeLevelAndConstructorLevelBinding

### The exact TCK version

CDI TCK version 4.0.7

### The implementation being tested, including name and company

Apache OpenWebBeans 4.0.0-SNAPSHOT from the Apache Software Foundation

### A full description of why the test is invalid and what the correct behavior is believed to be

In both of the tests mentioned above, at least 2 interceptors in the stack have `@Priority(2000)`

Per the interceptor specification 2.1, Section 5.2.1, it's explicitely written `If more than one interceptor has the same priority, the relative order of those interceptors is undefined.`. The 2 tests mentioned above assert a specific order which is against the specification.

NOTE: in CDI some sections like, 2.8.5.2 which relates to Observer ordering also have a similar mentioned, `The order of more than one observer with the same priority is undefined and the observer methods are notified therefore in a non predictable order.` which is consistent.

### Any supporting material; debug logs, test output, test logs, run scripts, etc.

> [ERROR]   ConstructorInterceptionTest>Arquillian.run:138->testMultipleConstructorLevelBinding:72 ActionSequence [name=default, data=[BravoInterceptor, AlphaInterceptor2, BeanWithMultipleConstructorLevelBinding]] and expected sequence differ on the index 0. expected [AlphaInterceptor2] but found [BravoInterceptor]
[ERROR]   ConstructorInterceptionTest>Arquillian.run:138->testTypeLevelAndConstructorLevelBinding:90 ActionSequence [name=default, data=[BravoInterceptor, AlphaInterceptor1, BeanWithConstructorLevelAndTypeLevelBinding]] and expected sequence differ on the index 0. expected [AlphaInterceptor1] but found [BravoInterceptor]

**Comment by manovotn** [comment]
This seems correct, in both tests the interceptors have the same priority.
@jeanouii thanks for the report, would you care to send a PR to fix this?

**Comment by jeanouii** [comment]
Thanks for the quick reply and guidance.
I'm happy to do so, but looks like I found some other related failures, so I'll create another challenge issue and then address the fixes all together
