### ISSUE TITLE
org.jboss.cdi.tck.interceptors.tests.bindings.overriding.InterceptorBindingOverridingTest

### ISSUE THREAD

**Issue by jeanouii** [jakartaee/cdi-tck#420]
Per the current [TCK Process documentation](https://jakarta.ee/committees/specification/tckprocess/), please find bellow a challenge related to CDI TCK. Can someone please add the `challenge` label which is required by the TCK Process but not available to everyone to add.

### The relevant specification version and section number(s)

https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html
Section 1.2.5. Relationship to Jakarta Interceptors

https://jakarta.ee/specifications/interceptors/2.1/jakarta-interceptors-spec-2.1.html
Section 5.2.1. Use of the Priority Annotation in Ordering Interceptors

### The coordinates of the challenged test(s)

Only following test in the class is related to the challenge 

* testInterceptorBindingOverriden

### The exact TCK version

CDI TCK version 4.0.7

### The implementation being tested, including name and company

Apache OpenWebBeans 4.0.0-SNAPSHOT from the Apache Software Foundation

### A full description of why the test is invalid and what the correct behavior is believed to be

The test is composed of a simple bean Pony with 2 classes level interceptors and 1 method level interceptor overriding one of the 2 class lever interceptor. So in the end, we have a list of 2 interceptors, one being the method interceptor and the other one is the remaining class level interceptor (because the other one got overriden). 

Section 5.2. Interceptor Ordering Rules of Interceptor 2.1 also refers to ordering using @Priority annotation and says

> All interceptors specified using interceptor binding annotations visible on the target class (e.g., specified on the class or visible on the class because they were declared with the Inherited annotation) are combined with all binding annotations on the target method and sorted by the priorities specified by the Priority annotation; and then the interceptor methods are invoked in order of priority

In this sentence the last part explicitely says the final list needs to be sorted by the @Priority annotation. And once again, all same priority so not deterministic order.

````
        // getAge() returns 3, SlowAgingInterceptor adds one (4) and NegatingInterceptor negates (-4)
        assertEquals(pony.getAge(), -4);
````

This could be first negate 3 so you get -3 and add 1 so you get -2 and not -4.

### Any supporting material; debug logs, test output, test logs, run scripts, etc.

> [ERROR]   InterceptorBindingOverridingTest>Arquillian.run:138->testInterceptorBindingOverriden:61 expected [-4] but found [-2]

**Comment by mkouba** [comment]
For the record - there can be more failures like this. The `InterceptorBindingOverridingTest` [originally used a beans.xml descriptor](https://github.com/jakartaee/cdi-tck/commit/021f446d5bceffc7169ec463671236c04aeb2022#diff-c2cc0231031e61d44e0f0203a7a911513957fb6038d337b1e5c6742cf970672d) where the ordering of interceptors was clearly defined.

**Comment by manovotn** [comment]
Martin has a really good, that commit is the source of problems you encountered in #418 and #419 as well - you can see the test classes there and their `beans.xml` removed.
Such huge commits are hard to review and Weld probably accidentally passed it (due to how it chooses to order interceptors with conflicting priorities by default). Now, the removal itself is intended but the priorities need to be shifted accordingly.

We should probably review that commit in terms of looking for all the places where there was a removal of `.withBeansXml(...)` invocation. There are, give or take, 25 such cases, not all of which necessarily lead to bad test. I could try to take a look next week.
@jeanouii FYI^^, it might save you quite a few issues here :)

**Comment by manovotn** [comment]
It is indeed useful, thanks for bringing it up. It is understandable you won't go through the history, we just brought it up as we recalled there were massive changes to TCKs to split them into Lite and Full testsuites.

**Comment by jeanouii** [comment]
I can't find any more ordering related issues. I'm gonna submit a PR to fix the tests. What is the good way to go?

One PR per issue?
One PR for the 4 issues has they are related?

**Comment by manovotn** [comment]
@jeanouii I think you can do one PR with complete set of changes and just reference all the issues in it.

**Comment by jeanouii** [comment]
Works for me, I'll checkout the code and do that asap.
Thanks again for the quick follow up
