### ISSUE TITLE
org.jboss.cdi.tck.tests.full.context.passivating.dependency.builtin.BuiltinBeanPassivationDependencyTest

### ISSUE THREAD

**Issue by jeanouii** [jakartaee/cdi-tck#424]
Per the current [TCK Process documentation](https://jakarta.ee/committees/specification/tckprocess/), please find bellow a challenge related to CDI TCK. Can someone please add the `challenge` label which is required by the TCK Process but not available to everyone to add.

### The relevant specification version and section number(s)

https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html

### The coordinates of the challenged test(s)

Only following test in the class are related to the challenge 

* testInjectionPoint

### The exact TCK version

CDI TCK version 4.0.7

### The implementation being tested, including name and company

Apache OpenWebBeans 4.0.0-SNAPSHOT from the Apache Software Foundation

### A full description of why the test is invalid and what the correct behavior is believed to be

The test essentially passivates (serialize) a bean instance and activates it back (deserialize). Then it asserts that the bean is the same. When comparing the bean instance before serialization and the bean instance after deserialization, the test assumes Annotated implements equals() which isn't required or specified anywhere in the spec or in the javadoc.

> assertEquals(inspectorCopy.getInjectionPoint().getAnnotated(), inspector.getInjectionPoint().getAnnotated());

The section 3.9.4. Alternative metadata sources defines the interface but does not require equals()/hashcode() to be implemented. It only says 

> The interface jakarta.enterprise.inject.spi.Annotated exposes the overriding annotations and type declarations.

````
public interface Annotated {
    Type getBaseType();
    Set<Type> getTypeClosure();
    <T extends Annotation> T getAnnotation(Class<T> annotationType);
    <T extends Annotation> Set<T> getAnnotations(Class<T> annotationType);
    Set<Annotation> getAnnotations();
    boolean isAnnotationPresent(Class<? extends Annotation> annotationType);
}
````

### Any supporting material; debug logs, test output, test logs, run scripts, etc.

> java.lang.AssertionError:
Expected :Annotated Field 'inspector', Base Type : class org.jboss.cdi.tck.tests.full.context.passivating.dependency.builtin.Inspector,Type Closures : null,Annotations : [@jakarta.inject.Inject()],Java Member Name : inspector
Actual   :Annotated Field 'inspector', Base Type : class org.jboss.cdi.tck.tests.full.context.passivating.dependency.builtin.Inspector,Type Closures : null,Annotations : [@jakarta.inject.Inject()],Java Member Name : inspector

**Comment by manovotn** [comment]
@jeanouii technically you are right but please consider this - look at the exact same test, [two lines above where there is `equals` for `Bean<?>`.](https://github.com/jakartaee/cdi-tck/blob/master/impl/src/main/java/org/jboss/cdi/tck/tests/full/context/passivating/dependency/builtin/BuiltinBeanPassivationDependencyTest.java#L98)
As far as I can tell, spec also doesn't explicitly say that `Bean#equals` should be implemented, yet it's not an issue.
And this goes for most of CDI spec, it doesn't really define whether interface impls should have equals/hashcode.
So I don't know how much of it is actually spec fault and how much is simply implied expectation. Personally I don't see much benefit in polluting every spec API by explicitly saying that you really need to implement equals/hashCode but that might be just me.

So, while it's simple to "fix" this test by instead asserting attributes of the `Annotated`, it doesn't really solve the underlying problem. WDYT @jeanouii @Ladicek?

**Comment by Ladicek** [comment]
I tend to agree with @jeanouii. A lot of equality assertions in the TCK actually verify _identity_ (which is the default definition of equality in Java). Passivation obviously cannot preserve identity, so the test must not verify it, and no other equality is defined.

I'm not sure about `Bean`, but specifically for `Annotated`, we could verify equality of the underlying `java.lang.reflect` object:

- `AnnotatedMember`: `getJavaMember()`
- `AnnotatedParameter`: `getJavaParameter()`
- `AnnotatedType`: `getJavaClass()`

That should be enough in my opinion.

**Comment by manovotn** [comment]
> That should be enough in my opinion.

Sure, I agree we can fix that.
All I am saying is that it isn't a single unclear case and we might want to address this on the spec level by stating whether asserting equality is expected or not.

**Comment by Ladicek** [comment]
We discussed this on the CDI call today and agreed we should discuss the "unspecified equality" problem separately from this. At the moment, CDI doesn't require `Annotated` implementations to provide equality, so the TCK shouldn't rely on it. Marking as _accepted_.

**Comment by jeanouii** [comment]
In most case, you are correct it's implied and I also agree it's not useful to polute the spec with it.
But for serialization/deserialization it obviously can't work if we don't clearly define how to compare before and after serialization.

The assert is obviously the issue and I'm happy to provide you with a PR to compare the underlying type until the discussion gets resolved more widely.

**Comment by Ladicek** [comment]
PR would be nice :-) Thanks in advance!

**Comment by jeanouii** [comment]
Hello guys,

I created a small PR to compare the base class and the set of Annotations.
Should be enough to address the issue as the rest is already tested.

https://github.com/jakartaee/cdi-tck/pull/430

Have a wonderful week.
