### ISSUE TITLE
TCK Challenge: testConversationPropagatedAjax using HTMLUnit is incompatible with modern Typescript implementations

### ISSUE THREAD

**Issue by brideck** [jakartaee/cdi-tck#434]
**Challenged Tests:**
[org.jboss.cdi.tck.tests.context.conversation.LongRunningConversationPropagatedByFacesContextTest#testConversationPropagatedAjax](https://github.com/jakartaee/cdi-tck/blob/master/web/src/main/java/org/jboss/cdi/tck/tests/context/conversation/LongRunningConversationPropagatedByFacesContextTest.java#L117)

**TCK Version:**
Jakarta CDI 4.0.x

**Tested Implementation:**
Open Liberty -- containing Weld & MyFaces 4.0.0

**Description:**
After updating to MyFaces 4.0.0-RC5, the challenged test fails with:
```
[ERROR] testConversationPropagatedAjax(org.jboss.cdi.tck.tests.context.conversation.LongRunningConversationPropagatedByFacesContextTest)  Time elapsed: 0.474 s  <<< FAILURE!
com.gargoylesoftware.htmlunit.ScriptException: missing formal parameter (http://localhost:9080/LongRunningConversationPropagatedByFacesContextTest7339fc7fa2b6132946e730d2c961837c417694c/jakarta.faces.resource/faces.js.jsf?ln=jakarta.faces#2)
        at org.jboss.cdi.tck.tests.context.conversation.LongRunningConversationPropagatedByFacesContextTest.testConversationPropagatedAjax(LongRunningConversationPropagatedByFacesContextTest.java:122)
Caused by: net.sourceforge.htmlunit.corejs.javascript.EvaluatorException: missing formal parameter (http://localhost:9080/LongRunningConversationPropagatedByFacesContextTest7339fc7fa2b6132946e730d2c961837c417694c/jakarta.faces.resource/faces.js.jsf?ln=jakarta.faces#2)
        at org.jboss.cdi.tck.tests.context.conversation.LongRunningConversationPropagatedByFacesContextTest.testConversationPropagatedAjax(LongRunningConversationPropagatedByFacesContextTest.java:122)
```

With 4.0.0-RC5, MyFaces has moved away from Javascript in Favor of Typescript and also raised the base level towards more modern browsers. Ecmascript is now ES 2015 and the dom level supports HTMLForm Objects XMLHttpRequest and querySelectorAll.

HTMLUnit uses the underlying Rhino Engine, which is stuck and has been for quite a while on ES5 level (and very likely also a really old dom level). On top of that, the ES5 level supported is somewhat buggy.

See the following link showing the current status of Rhino: https://mozilla.github.io/rhino/compat/engines.html

Simply by dropping old standards and trying to ramp up to ES2015 we cannot run this TCK test against the new faces.js codebase anymore.

In the Faces TCK, a [challenge](https://github.com/jakartaee/faces/issues/1722) was opened and extensive work has been done to create identical implementations using headless Chrome and the Selenium Webdriver for any affected Ajax tests. We would request that similar work occur here, or that the test be excluded until such work could occur.

**Comment by manovotn** [comment]
This isn't the only test using htmlunit - there is quite a few in the `web` module of TCKs and this change would affect all of them.
Furthermore, running Selenium on CI was always tricky and would require work too (and I am not familiar with whether it's even possible on Eclipse instances or whether there are some limitations?).

Either way, it'd require some non trivial amount of work to rewrite and make sure it works and tests the same things.
@brideck are you willing to submit such a PR?

**Comment by starksm64** [comment]
There is this Selenium driver for htmlunit, perhaps than can be used in place of Rhino?

https://github.com/SeleniumHQ/htmlunit-driver

**Comment by brideck** [comment]
> There is this Selenium driver for htmlunit, perhaps than can be used in place of Rhino?
> 
> https://github.com/SeleniumHQ/htmlunit-driver

I'm going to tinker a bit with this. Maybe I can come up with something that works, but the better solution would be to exclude this single test for now (to allow for Faces modernization) and then make an attempt to modernize the entire CDI TCK for the next release.

**Comment by volosied** [comment]
Just for more context -- the exact problem HTMLUnit is encountering is with the rest parameters. There's an existing issue open in Rhino: `https://github.com/mozilla/rhino/issues/652` & HTMLUnit: `https://github.com/HtmlUnit/htmlunit/issues/158` 

MyFaces recently modernized its scripts which now use this newer syntax, as Brian mentioned, and so HTMLUnit, unfortunately, is now failing as it can't handle this newer code.

**Comment by brideck** [comment]
> > There is this Selenium driver for htmlunit, perhaps than can be used in place of Rhino?
> > https://github.com/SeleniumHQ/htmlunit-driver
> 
> I'm going to tinker a bit with this. Maybe I can come up with something that works, but the better solution would be to exclude this single test for now (to allow for Faces modernization) and then make an attempt to modernize the entire CDI TCK for the next release.

I made some changes locally to try this out, and just using Selenium with the HTMLUnit driver doesn't change anything. It just transitions into the same HTMLUnit code a little farther down the stack.

**Comment by brideck** [comment]
> This isn't the only test using htmlunit - there is quite a few in the `web` module of TCKs and this change would affect all of them. It'd require some non trivial amount of work to rewrite and make sure it works and tests the same things. @brideck are you willing to submit such a PR?

Here's a PR to add a Selenium implementation of just the one test -- https://github.com/jakartaee/cdi-tck/pull/437

A few notes:
- The Selenium code was yoinked from the Faces TCK, and I left all of the pre-existing copyright notices in place. If any of that is a problem, I'm not sure of the solution.
- The Selenium path is opt-in only, gated by a system property that an implementation using MyFaces (like Open Liberty) would provide in their TCK runner pom.
- I've not actually formally built this to make sure it produces a TCK with all the parts in the right place. I was very much sandboxing this on the fly.

It would be simple (though not trivial) to build out from here with Selenium implementations of the other HTMLUnit tests. I left it at just this one both because it suits the immediate needs of the challenge and because the CDI community might want to develop a more sophisticated means of providing both Selenium and HTMLUnit and/or just do a wholesale replacement of HTMLUnit.
