### ISSUE TITLE
Publish 4.0.7 tck to https://jakarta.ee/specifications/cdi/4.0/

### ISSUE THREAD

**Issue by dblevins** [jakartaee/cdi-tck#435]
Minor action item.  Looks like we haven't yet published the 4.0.7 TCK zip at:

 - https://jakarta.ee/specifications/cdi/4.0/

**Comment by manovotn** [comment]
I have no idea how to do that - I naively thought the release Jenkins job would do it but I guess I was wrong.
@starksm64 might know?

**Comment by jeanouii** [comment]
You have to PR https://github.com/jakartaee/specifications/tree/master/cdi/4.0 and update the index file. I can review it afterwards or help if you need

**Comment by manovotn** [comment]
This has been resolved long time ago, closing.
