### ISSUE TITLE
Post construct interceptor missing an invocation context parameter

### ISSUE THREAD

**Issue by manovotn** [jakartaee/cdi-tck#448]
The `org.jboss.cdi.tck.interceptors.tests.contract.lifecycleCallback.SheepInterceptor` declares a `@PostConstruct` method which violates interceptor spec requirements.

Namely in [this section](https://jakarta.ee/specifications/interceptors/2.1/jakarta-interceptors-spec-2.1.html#interceptor-methods-for-lifecycle-event-callbacks), the following is stated:

> Lifecycle callback interceptor methods declared in an interceptor class or superclass of an interceptor class must have one of the following signatures:
>* `void <METHOD>(InvocationContext)`
>* Object <METHOD>(InvocationContext)

Here is a [link](https://github.com/jakartaee/cdi-tck/blob/4.0.9/impl/src/main/java/org/jboss/cdi/tck/interceptors/tests/contract/lifecycleCallback/SheepInterceptor.java#L32-L35) to the current method declaration which lacks the `InvocationContext` parameter.

The only test using this interceptor asserts that this callback *does not* get invoked which is probably why it didn't get noticed earlier.

~~EDIT: I intentionally didn't mark the issue as a challenge but if we encounter an impl having issues with it, it is certainly an option.~~
After some though, I added the challenge label.

**Comment by Ladicek** [comment]
This is a tiny issue that I believe can't negatively affect anyone, so we can just fix it directly.
