### ISSUE TITLE
Custom CreationalContext used by TCK is not required to be supported

### ISSUE THREAD

**Issue by manovotn** [jakartaee/cdi-tck#453]
On several places, TCK tests use a custom `CreationalContext` implementation - `org.jboss.cdi.tck.util.MockCreationalContext`.

However, the specification doesn't state that arbitrary custom creational contexts should be supported in general nor is any test asserting that claim.
Plus it's not realistic either as the API is very minimal and both impls I am familiar with need a much richer internal API to handle CC and, in turn, expect that any CC they operate on is an instance of their internal implementation.

Now, this custom CC is used in two ways:

1. In tests where there is need to create any instance of CC
  1.1 An example can be seen [here](https://github.com/jakartaee/cdi-tck/blob/master/impl/src/main/java/org/jboss/cdi/tck/tests/context/GetFromContextualTest.java#L54)
  1.2 These can be easily replaced by `BeanManager#createCreationalContext()` without changing what the test does - as such these can be altered even for 4.x releases without need for exclusion
2. In tests that need to verify what's happening in the CC; basically an introspection of how the CC should work
  2.1 An example is [this test](https://github.com/jakartaee/cdi-tck/blob/master/impl/src/main/java/org/jboss/cdi/tck/tests/implementation/simple/lifecycle/SimpleBeanLifecycleTest.java#L95) 
  2.2 We can replace these test with new TCK SPI which introduces and inspectable CC provided by the impl and therefore still being based on their internal impl. _This doesn't change the nature of what is tested, it merely let's the integrator provide an instance of CC which the TCK can inspect and verify._

@Ladicek already created a proposal for the TCK SPI that could be used in future version of TCKs (minor/major update); see https://github.com/jakartaee/cdi-tck/pull/452

For current version of TCKs linked to CDI 4.0, I'd suggest we exclude any tests that rely on introspection of the CC. WDYT?

**Comment by Ladicek** [comment]
I obviously agree :-)
