### ISSUE TITLE
DependentContextTest#testDependentScopedInterceptorsAreDependentObjectsOfBean() does not test the spec assertion

### ISSUE THREAD

**Issue by mkouba** [jakartaee/cdi-tck#454]
The [`org.jboss.cdi.tck.tests.context.dependent.DependentContextTest#testDependentScopedInterceptorsAreDependentObjectsOfBean()`](https://github.com/jakartaee/cdi-tck/blob/4.1.0.Alpha3/impl/src/main/java/org/jboss/cdi/tck/tests/context/dependent/DependentContextTest.java#L446-L463) test method does not test the [linked spec assertion](https://github.com/jakartaee/cdi-tck/blob/4.1.0.Alpha3/impl/src/main/resources/tck-audit-cdi.xml#L2822-L2826):

> Instances of interceptors or decorators with scope `@Dependent` are dependent objects of the bean instance they decorate.

It merely asserts that if `CreationalContext#release()` is called then the `TransactionalInterceptor#destroy()` callback is invoked because the `AccountTransaction` bean is destroyed. And even this assert is questionable because the test should rather call `Bean#destroy()` instead; `CreationalContext#release()` should destroy the dependent objects and not the bean itself.

In fact, this assertion should be `testable=false` because there's no reasonable way to test it (an interceptor may not declare its own `@PreDestroy` callback).

I'd recommend to mark the assertion as `testable=false` and remove the test method completely.

**Comment by Ladicek** [comment]
That is a good idea! I'll see if I can rewrite the test like that.

**Comment by Ladicek** [comment]
Seems to work well -- submitted #462. Thanks @Azquelt!

**Comment by manovotn** [comment]
Very good idea indeed, that should do the trick!

**Comment by manovotn** [comment]
Added the `accepted` label as we seem to agree that the current state isn't OK and we now have a way to test it properly

**Comment by manovotn** [comment]
As discussed in the meeting today, the solution to this challenge needs to be a test exclusion.
The challenge is correct and so is the fix. However, previous version of the TCK only passed with Weld due to a Weld bug (see https://issues.redhat.com/browse/WELD-2743).
Therefore, in order for Weld releases to keep passing latest TCKs, the correct course of action is excluding this test for `4.0.x` and re-enabling them for 4.1. Otherwise, we'll repeat the situation where older Weld version won't pass latest TCKs.

I'll send a PR for this.

**Comment by manovotn** [comment]
> As discussed in the meeting today, the solution to this challenge needs to be a test exclusion. The challenge is correct and so is the fix. However, previous version of the TCK only passed with Weld due to a Weld bug (see https://issues.redhat.com/browse/WELD-2743). Therefore, in order for Weld releases to keep passing latest TCKs, the correct course of action is excluding this test for `4.0.x` and re-enabling them for 4.1. Otherwise, we'll repeat the situation where older Weld version won't pass latest TCKs.
> 
> I'll send a PR for this.

@Ladicek @Emily-Jiang it seems that I was mistaken and that we got a little confused in the mtg discussion yesterday :)
Weld actually passes this test (after changes made in https://github.com/jakartaee/cdi-tck/pull/462) even on older versions - I tried with 5.0.0.Final.
What wouldn't work is Weld 5.1.1 (not yet released) with *older* TCK version, such as 4.0.9. However, that doesn't really matter as the requirement is for all impl versions to pass the most recent TCKs.
Therefore, no action is needed here - sorry for the hassle.
