### ISSUE TITLE
org.jboss.cdi.tck.tests.interceptors.definition.InterceptorDefinitionTest#testInterceptorsImplementInterceptorInterface uses internal type

### ISSUE THREAD

**Issue by Ladicek** [jakartaee/cdi-tck#455]
This test uses a helper class `HierarchyDiscovery` to find the set of interface types that an interceptor metadata class (implementation of `jakarta.enterprise.inject.spi.Interceptor`) implements and then verifies that a parameterized type `Interceptor` is among them. It expects that a `ParameterizedTypeImpl` is used to represent a parameterized type, which is an internal implementation detail of `HierarchyDiscovery`. If the the interceptor metadata class doesn't have a generic signature (which happens for our implementation, ArC, that generates the implementation at compile time), the parameterized type of `Interceptor` isn't the TCK's internal `ParameterizedTypeImpl`, but the JDK's `ParameterizedTypeImpl`. They both implement `java.lang.reflect.ParameterizedType`, which is something the test should use in my opinion.

**Comment by manovotn** [comment]
The test doesn't even need to rely on the internal param. type impl for what it verifies so +1
