### ISSUE TITLE
org.jboss.cdi.tck.tests.context.DestroyForSameCreationalContext2Test isn't marked as "full" and uses session context and custom `Contextual`

### ISSUE THREAD

**Issue by Ladicek** [jakartaee/cdi-tck#457]
The test `DestroyForSameCreationalContext2Test` repeats the exact same 2 assertions against a session context and a request context. To do that, it also uses a custom implementation of the `Contextual` interface. This test isn't marked as "full", and isn't a `full` package, because it makes sense for CDI Lite as well -- except CDI Lite implementations are not required to provide the session context and don't necessarily have to support custom implementations of `Contextual`.

I believe we should move the test to the `full` package.

**Comment by manovotn** [comment]
I agree, we likely missed this test initially. All tests using session context should have been either rewritten or moved to `full`.
