### ISSUE TITLE
InterceptorBindingInheritanceTest relies on undefined behavior

### ISSUE THREAD

**Issue by Ladicek** [jakartaee/cdi-tck#468]
Similarly to #464, two tests in `InterceptorBindingInheritanceTest` rely on recursive interception being prevented by the container, which is not defined properly anywhere and is unrelated to the stated purpose of the test (which is inheritance of interceptor binding annotations).

It is relatively straightforward to modify the test to not trigger recursive interception, which is what I propose we do.

**Comment by manovotn** [comment]
Good find, this really should have been part of #464 but I missed it.

**Comment by struberg** [comment]
Maybe this problem does not bubble up in Weld as you create equals and hashcode method which equal the proxy with their respective contextual instances? If so then please point me to the section where this is defined please.

**Comment by Ladicek** [comment]
Contextual reference for a pseudo-scoped bean is the contextual instance, so better be careful with the wording. There's no client proxy involved.

However, I can see that this might be problematic if the CDI implementation in question implements interception using proxies (instead of subclasses). I vaguely remember thinking that this is not a valid implementation strategy at some point, but I no longer remember why. I might have easily been mistaken.

I'll take another look on the test; I guess we could actually use a `static` field (we currently don't) to sidestep all the possible troubles.

**Comment by struberg** [comment]
OWB does implement the proxy via subclassing. But how it does it is seemingly different to Weld. A static field would be perfectly fine for us - thanks Ladicek!

**Comment by Ladicek** [comment]
ArC and Weld implement interception without proxying -- we generate a subclass of the bean class where we override intercepted methods such that invocation of the intercepted method starts the interception chain. An instance of _that_ class becomes the contextual instance. It seems to me that you implement interception through proxying, so you need to differentiate between a "proper" contextual instance and an "interception proxy" instance.

That is a little head-exploding situation :-), but the TCK obviously needs to support it. I'll try to submit a PR in a bit.

**Comment by Ladicek** [comment]
Here's a proposed fix for the CDI TCK 4.0 branch: https://github.com/Ladicek/cdi-tck/commits/proxy-based-interception-fix-4.0 It works fine with ArC and Weld, could you please verify if that works for you? Thanks!

**Comment by Ladicek** [comment]
I submitted a PR for the `master` branch (for CDI 4.1). I can also submit a fix for the 4.0 branch, or we can add exclusions.

**Comment by manovotn** [comment]
> I submitted a PR for the `master` branch (for CDI 4.1). I can also submit a fix for the 4.0 branch, or we can add exclusions.

I don't mind the fix but I think we mostly agreed to do exclusions for these cases; a comment explaining why would be neat if you decide for the exclusion.

**Comment by Ladicek** [comment]
Yeah, since 4.1 is near, I think we should go for exclusions. I only uploaded a branch with a fix for 4.0 so that you could verify it. (The PR I did open is for 4.1.)

**Comment by struberg** [comment]
> ArC and Weld implement interception without proxying -- we generate a subclass of the bean class where we override intercepted methods such that invocation of the intercepted method starts the interception chain. An instance of _that_ class becomes the contextual instance. It seems to me that you implement interception through proxying, so you need to differentiate between a "proper" contextual instance and an "interception proxy" instance.
> 
> That is a little head-exploding situation :-), but the TCK obviously needs to support it. I'll try to submit a PR in a bit.

To go into detail a bit more because I feel there is potential for non portability ahead in the interceptor area:
Afair the EE umbrella spec did specify that interceptors only must get triggered when the bean gets invoked via a 'business method'. And somewhere else this is defined as an _external_ call via the 'business interface'. And while for no-interface-views this is just the plain java class even there the 'business method' definition still applies. So essentially if you call an intercepted method of a contextual instance from within that very class, then the interceptor does not get triggered. Not sure how this is done in Weld if the contextual instance is the intercepted class itself?
