### ISSUE TITLE
EmptyBeansXmlDiscoveryTest has incorrect deployment configuration

### ISSUE THREAD

**Issue by manovotn** [jakartaee/cdi-tck#470]
In my attempt to update Arquillian deps in Weld(https://github.com/weld/core/pull/2846), I noticed that `EmptyBeansXmlDiscoveryTest` started failing.
A recent fix in Arquillian (https://github.com/arquillian/arquillian-core/pull/440) correctly exposes erroneous setup of this test which was previously falsely passing and would pass regardless of what would be in the test.

Underlying cause is a `NoClassDefFound` error and further digging showed that the test deployment lacks the `AbstractTest` superclass (and possibly other classes).
Said test uses a manual setup via `ShrinkWrap.create(WebArchive.class).addClasses(...)` (beucase it needed a truly empty beans.xml added) whereas other TCK tests use `WebArchiveBuilder()` API. Turns out `WebArchiveBuilder` does a bunch of things for the test automagically, including adding `AbstractTest` class into the deployment.

The test can be easily rewritten to make use of the `WebArchiveBuilder` which solves the issue and should make it (correctly) pass on al Arq. versions. I have the changes locally and will submit a PR.

Since this problem is a combination of testng and Arq. core version, not all impls and test setups are affected - especially since you can do a lot of tweaks in Arq. adapters that each impl is using. Nonetheless, the test setup is still wrong. I wonder if perhaps Liberty is also seeing this if they update Arq. core to `1.7.0.Final`, maybe @Azquelt knows?

**Comment by Azquelt** [comment]
When this was raised, we were still using an older version of arquillian. When we upgraded to 1.7.0.Final, we do indeed have the same problem.

**Comment by manovotn** [comment]
> When this was raised, we were still using an older version of arquillian. When we upgraded to 1.7.0.Final, we do indeed have the same problem.

Thanks for verifying!
