### ISSUE TITLE
ProcessBeanAttributesNotFiredForBuiltinBean should only be checking for beans with @Default

### ISSUE THREAD

**Issue by manovotn** [jakartaee/cdi-tck#474]
`org.jboss.cdi.tck.tests.extensions.lifecycle.processBeanAttributes.builtin.ProcessBeanAttributesNotFiredForBuiltinBean` is a test that verifies following parts of the spec([1](https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#additional_builtin_beans)):

> A Jakarta EE or embeddable EJB container must provide the following built-in beans, all of which have qualifier `@Default`:
> ...
> a bean with bean type jakarta.servlet.http.HttpServletRequest, allowing injection of a reference to the HttpServletRequest

In combination with([2](https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#process_bean_attributes)):

> No [PBA] event is fired for any:
> * beans added programmatically using AfterBeanDiscovery.addBean(), or,
> * for any built-in beans.

However, the test has an extension that simply observers any PBA, regardless of bean attributes, and as soon as it detects PBA for any bean of that given type, it fails. I believe the extension in question should also inspect bean attributes and only fail if the bean has `@Default` qualifier as you can theoretically define any number of the beans with that given type that are not built-in hence should have PBA fired for them.

This was originally reported by @arjantijms in https://github.com/eclipse-ee4j/glassfish/issues/24049

**Comment by Ladicek** [comment]
That makes sense to me. We can't really detect whether the bean is built-in or not, but checking for the `@Default` qualifier is a reasonable approximation.
