### ISSUE TITLE
TCK Challenge: ObserverExceptionRethrownTest modify event type

### ISSUE THREAD

**Issue by jbescos** [jakartaee/cdi-tck#487]
**Describe the bug**
`ObserverExceptionRethrownTest#testNonTransactionalObserverThrowsNonCheckedExceptionIsRethrown` verifies that one exception happens when firing one String event.

In the case of Helidon, this exception is thrown on deployment `ObserverExceptionRethrownTest#createTestArchive` because Helidon container fires 2 String events on deployment. One to notify when beans are going to be deployed, and other when beans are deployed.

**To Reproduce**
N/A

**Expected behavior**
`TeaCupPomeranian` will handle a different event type, to throw the exception only when we want to throw it.

**Additional information**
TCK challenge for EE 10 (CDI 4.0) PR: https://github.com/jakartaee/cdi-tck/pull/488
PR for master: https://github.com/jakartaee/cdi-tck/pull/486

**Comment by jbescos** [comment]
PR for master: https://github.com/jakartaee/cdi-tck/pull/486

**Comment by Ladicek** [comment]
It's your call, obviously, but I'd suggest Helidon maybe also use a dedicated event type, or use a qualifier. An event type of `String`, unqualified, is overly broad and there's a big risk of overlap (as this challenge shows).

**Comment by Ladicek** [comment]
PRs merged, closing.

**Comment by manovotn** [comment]
> It's your call, obviously, but I'd suggest Helidon maybe also use a dedicated event type, or use a qualifier. An event type of `String`, unqualified, is overly broad and there's a big risk of overlap (as this challenge shows).

Fully agree but I didn't even suggest that as I assume this will be hard to remove anyway due to backward compatility.
