### ISSUE TITLE
TCK Challenge: Three TCK Core Profile tests depends on servlet-api

### ISSUE THREAD

**Issue by jbescos** [jakartaee/cdi-tck#490]
**Describe the bug**

In Helidon we have to pass TCK Core Profile tests, which includes some CDI TCK 4.0 tests that you can see in the next plugin configuration. Core Profile should not depend on servlet-api, but we see there are some tests that they depend on it.

```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <systemPropertyVariables>
                        <org.jboss.weld.construction.relaxed>false</org.jboss.weld.construction.relaxed>
                    </systemPropertyVariables>
                    <forkCount>1</forkCount>
                    <reuseForks>false</reuseForks>
                    <excludedGroups>cdi-full,se</excludedGroups>
                    <dependenciesToScan>
                        <dependency>jakarta.enterprise:cdi-tck-core-impl</dependency>
                    </dependenciesToScan>
                    <includes>
                        <include>org/jboss/cdi/tck/tests/**/*Test.java</include>
                        <include>org/jboss/cdi/tck/interceptors/DependentContextTesttests/**/*Test.java</include>
                    </includes>
                    <excludes>
                        <!-- https://github.com/jakartaee/cdi-tck/issues/485 -->
                        <exclude>org/jboss/cdi/tck/tests/definition/bean/types/ManagedBeanTypesTest.java</exclude>
                        <!-- https://github.com/jakartaee/cdi-tck/issues/487 -->
                        <exclude>org/jboss/cdi/tck/tests/event/observer/runtimeException/ObserverExceptionRethrownTest.java</exclude>
                    </excludes>
                </configuration>
            </plugin>
```
These are the test methods that depends on servlet-api:
```
[ERROR] Failures: 
[ERROR]   EventTest>Arquillian.run:138->testStaticObserverMethodInvoked:77 » UnsatisfiedResolution WELD-001334: Unsatisfied dependencies for type HttpRequestContext with qualifiers  
[ERROR]   ObserverNotificationTest>Arquillian.run:138->testObserverMethodNotInvokedIfNoActiveContext:82 » UnsatisfiedResolution WELD-001334: Unsatisfied dependencies for type HttpRequestContext with qualifiers  
[ERROR]   ConditionalObserverTest>Arquillian.run:138->testConditionalObserverMethodNotInvokedIfNoActiveContext:106 » UnsatisfiedResolution WELD-001334: Unsatisfied dependencies for type HttpRequestContext with qualifiers
```

**To Reproduce**
N/A

**Expected behavior**
In my opinion we can not use this line in tests, because that depends on servlet-api.

`Context requestContext = getCurrentConfiguration().getContexts().getRequestContext();`

I guess it s possible to test the same thing without depending on that.

**Additional information**

Helidon uses Weld. I was debugging it, and WeldWebModule will load required tests beans if it finds some servlet-api classes, that will not be there in core profile. This causes the failure.

**Comment by Ladicek** [comment]
This looks more like a bug in Weld or Weld integration to me. For some reason, Weld wants to use the servlet-based implementation of the request context, which shouldn't be necessary in these tests.

**Comment by Ladicek** [comment]
CC @manovotn

**Comment by manovotn** [comment]
> Helidon uses Weld. I was debugging it, and WeldWebModule will load required tests beans if it finds some servlet-api classes, that will not be there in core profile. This causes the failure.

Do you mean the `WeldWebModule#preBeanRegistration()` phase? That's where the bean should be registered and this should happen regardless of servlet-api; so long as this Weld module is found, it adds this set of beans.

> This looks more like a bug in Weld or Weld integration to me. For some reason, Weld wants to use the servlet-based implementation of the request context, which shouldn't be necessary in these tests.

It is not necessary here but this is coming from an implementation of CDI TCK SPI for `Contexts` which can be used anywhere in CDI TCK. Weld ([`ContextsImpl`](https://github.com/weld/core/blob/master/porting-package/src/main/java/org/jboss/weld/tck/ContextsImpl.java)) is trying to operate on the most common req. context object, which is the http version of it.

**Comment by manovotn** [comment]
There are several req. context impls in Weld and in theory we could try to use another one, but I am not sure that won't interfere with other testing setups (and Arq. containers linked with them) as they all use HTTP version - at least that's what I can see from a quick glance.

Note that the `ContextsImpl` is a TCK porting package impl and you could also supply a custom variant of the porting package using whichever other req. context impl you want (see [this javadoc for list of impls](https://github.com/weld/api/blob/master/weld/src/main/java/org/jboss/weld/context/RequestContext.java)).

In any case, as a TCK challenge I think it's invalid - it's a matter of implementation and integration so either Weld or Helidon setup issue. I'll add respective labels, but we can OFC keep discussing how to fix this for you.

**Comment by jbescos** [comment]
> Do you mean the `WeldWebModule#preBeanRegistration()` phase? That's where the bean should be registered and this should happen regardless of servlet-api; so long as this Weld module is found, it adds this set of beans.
> 

I think I was hitting with the debugger `WeldWebModule#postContextRegistration`. There is one condition that is not satisfied:
`if (Reflections.isClassLoadable(ServletApiAbstraction.SERVLET_CONTEXT_CLASS_NAME, WeldClassLoaderResourceLoader.INSTANCE)) {`

And then HttpRequestContext cannot be obtained when this line of the TCK is executed:
`Context requestContext = getCurrentConfiguration().getContexts().getRequestContext();`

That was my understanding, but note that I don't know the internals of Weld.

I tried to hack it, adding the servlet-api jar in the test execution module path. I bypassed that issue, but it was failing later because of other reason. And also that change made other tests to fail.

**Comment by manovotn** [comment]
> > Do you mean the `WeldWebModule#preBeanRegistration()` phase? That's where the bean should be registered and this should happen regardless of servlet-api; so long as this Weld module is found, it adds this set of beans.
> 
> I think I was hitting with the debugger `WeldWebModule#postContextRegistration`. There is one condition that is not satisfied: `if (Reflections.isClassLoadable(ServletApiAbstraction.SERVLET_CONTEXT_CLASS_NAME, WeldClassLoaderResourceLoader.INSTANCE)) {`

Uh, I ran out of caffeine apparently, you are correct, I missed this line.
Right, so you will either need to have a custom TCK porting package with your impl of `Contexts` SPI, or Weld will need to use a different one.
Alternatively, Weld's `ContextsImpl` could try to do a similar servlet API class check and use a fallback req. context impl in such a case.
I'll try a few things and get back to you; if we go for the fallback, I'd appreciate if you could test it out with your Helidon setup.

**Comment by jbescos** [comment]
Sure, I can test whatever you need. Thank you for your help.

I will also try to extend Weld's `ContextsImpl` to modify that `#getRequestContext()` method. I cannot do it right now, but later today or tomorrow I think I will be able to make some progress there.

**Comment by manovotn** [comment]
Looking closer at these tests, all of those that leverage `#getRequestContext()` are `@Test(groups = INTEGRATION)` which means they are run in full EE environment (such as with WildFly). In this case, Weld always has an active HTTP req. context - IIRC, this stems from Arq. container setup and protocol used (Servlet protocol in this case).
In other words, I cannot change Weld's `ContextsImpl` to always use another variant of req. context.

There is a similar issue with the fallback approach - I simply do not know what Helidon uses and it doesn't need to be universal for other Arq. adapters either. For instance Weld's embedded container (which runs all but `INTEGRATION` test groups) uses bound req. contex, [a snippet of which you can see here](https://github.com/arquillian/arquillian-container-weld/blob/master/impl/src/main/java/org/jboss/arquillian/container/weld/embedded/LifecycleHandler.java#L85-L107), but you might as well use the unbound version. Can you point me to the adapter Helidon uses?

> I will also try to extend Weld's ContextsImpl to modify that #getRequestContext() method. I cannot do it right now, but later today or tomorrow I think I will be able to make some progress there.

Note that you might also need changes to other method related to activation/deactivation of context (such as the association of the storage for bound req. context).

**Comment by jbescos** [comment]
I didn't notice that `@Test(groups = INTEGRATION)`

As Helidon is not full EE, I guess that group should be excluded.

**Comment by manovotn** [comment]
> As Helidon is not full EE, I guess that group should be excluded.

Glad I could help.
I was surprised you are running those as well but thought it was intentional :)
If you are looking into Jakarta Core compatibility (or CDI Lite), I think you should exclude it.
Take a look at this [TCK reference doc](https://jakartaee.github.io/cdi-tck/), namely section `4.4. Using the CDI TCK with the Jakarta EE Core Profile`
