### ISSUE TITLE
Updated to Java SE 17 for build and use SE 11 as build target

### ISSUE THREAD

**Issue by Ladicek** [jakartaee/cdi-tck#512]
Due to the dependency on JPA 3.2.0-M1, the CDI TCK doesn't build with Java 11 anymore. It feels like we should at least bump the various properties in the POMs to signal that 17 is the minimum now.

**Comment by manovotn** [comment]
@starksm64 wasn't 11 the agreed on minimum for all specs?

**Comment by Emily-Jiang** [comment]
> @starksm64 wasn't 11 the agreed on minimum for all specs? Or are the TCKs allowed to differ?

There is no agreed minimum Java version. Java 21 is the EE 11 compile version but some spec uses a lower version of the Java.

**Comment by Emily-Jiang** [comment]
For Jakarta Persistence, [its plan review](https://jakarta.ee/specifications/persistence/3.2/) says the minimum version is Java 17. This means CDI should update its minimum Java version to be Java 17 as well.

**Comment by starksm64** [comment]
@manovotn No, technically the minimum could be 21 for the TCK as that is what component specs are free to choose. I have raised it to 17 for now as that is what JPA required. We can fine tune the modules and have the core compile with 11 and the Web will move to the platform, so it won't impact the remaining core TCK.

**Comment by starksm64** [comment]
So we can leave this at SE 11 as the target and use a Java SE 17 JDK to compile to that target to avoid issues with the references to the EL interfaces used by the BeanManager.
