### ISSUE TITLE
Create TCK coverage for programmatic access to assignability rules for observer methods and typesafe resolution

### ISSUE THREAD

**Issue by manovotn** [jakartaee/cdi-tck#518]
CDI issue - https://github.com/jakartaee/cdi/issues/498
CDI PR - https://github.com/jakartaee/cdi/pull/700

We don't need to go in-depth on the assignability itself as those are covered elsewhere.
Instead, we should mostly test some basic cases plus the fact that implicit qualifiers are added automatically.

**Comment by Azquelt** [comment]
I will work on this unless someone else is already doing so.

**Comment by manovotn** [comment]
Sure, that would be great!
