### ISSUE TITLE
Synchronize on Weld release for a  4.1.0.Beta1 TCK release

### ISSUE THREAD

**Issue by starksm64** [jakartaee/cdi-tck#539]
I would like to synch on a Weld release that picks up the 4.1.0.Beta1 cdi api update so we can produce a 4.1.0.Beta1 cdi tck that includes the outstanding PRs. I merged #518  assignability tests, #502 looks ready, and then #532 should be ready.

**Comment by manovotn** [comment]
Yes, I intend to work on that next.

#502 should definitely get in - I will be focusing on getting that working in Weld next.
As for https://github.com/jakartaee/cdi-tck/pull/532, I am not sure that should be in TCK Beta1 as the CDI API Beta1 doesn't contain the spec text removal either (https://github.com/jakartaee/cdi/commits/main/).
Either way, that should be a minor thing WRT to having a passing impl anyway.

**Comment by starksm64** [comment]
That is fine, I can do a Beta 2 that just has the integration spec/tck removals next week.

**Comment by starksm64** [comment]
@manovotn Is there an ETA for the next Weld release? Is there anything you need help with?

**Comment by manovotn** [comment]
I was preoccupied elsewhere, I am working on it now.

The list of known issues is over at [JIRA](https://issues.redhat.com/projects/WELD/versions/12415474) but I will shift most of them past Beta to get a release out ASAP.
I already have release of Weld parent and Beta of Weld API and I am working on a PR for core - https://github.com/weld/core/pull/2911.

It is all built against M1 TCK (although I tested locally against `master`) as I tried to create a Beta TCK release yesterday but Jenkins probably had some maintenance and was inaccessible. Doesn't really matter though.

> Is there anything you need help with?

I think I can handle the Beta fine but if you want to help past that, I could use a hand with re-configuring the testing setup in Weld once the TCK web module gets migrated into platform TCKs. I assume this will happen for RC release, right?

**Comment by manovotn** [comment]
I think I should be able to get the release out tomorrow.

**Comment by starksm64** [comment]
> I think I can handle the Beta fine but if you want to help past that, I could use a hand with re-configuring the testing setup in Weld once the TCK web module gets migrated into platform TCKs. I assume this will happen for RC release, right?

Removal from the CDI TCK will happen after Beta1, which I'll do as soon as there is a new Weld release. I'll do an RC1 right after that has the Jakarta EE integration concerns in the spec and TCK removed. We are supposed to be targeting a final release this coming week.

**Comment by starksm64** [comment]
The 4.1.0.Beta1 TCK has been pushed out
