### ISSUE TITLE
Finalize the Jakarta API dependencies

### ISSUE THREAD

**Issue by starksm64** [jakartaee/cdi-tck#560]
For the staged final 4.1.0 version of the TCK we need to synch with the staged final versions of the CDI 4.1.0 dependencies as outlined in https://github.com/jakartaee/cdi/issues/770

Update the CDI dependencies to the following versions:
- [x] Jakarta Annotations: 3.0.0
- [x] Jakarta Expression Language: 6.0.0
- [x] Jakarta Interceptors: 2.2.0

**Comment by Ladicek** [comment]
Looks like this was done in #563?
